[2023-03-25T22:33:17.028+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data_v0.merge_weather_data scheduled__2023-03-25T21:00:00+00:00 [queued]>
[2023-03-25T22:33:17.038+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data_v0.merge_weather_data scheduled__2023-03-25T21:00:00+00:00 [queued]>
[2023-03-25T22:33:17.039+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T22:33:17.039+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 6
[2023-03-25T22:33:17.039+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T22:33:17.063+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): merge_weather_data> on 2023-03-25 21:00:00+00:00
[2023-03-25T22:33:17.067+0000] {standard_task_runner.py:55} INFO - Started process 386 to run task
[2023-03-25T22:33:17.071+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data_v0', 'merge_weather_data', 'scheduled__2023-03-25T21:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmp826qv8wd']
[2023-03-25T22:33:17.073+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask merge_weather_data
[2023-03-25T22:33:17.149+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data_v0.merge_weather_data scheduled__2023-03-25T21:00:00+00:00 [running]> on host 1e7d3c0923c5
[2023-03-25T22:33:17.222+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data_v0
AIRFLOW_CTX_TASK_ID=merge_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T21:00:00+00:00
[2023-03-25T22:33:17.314+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-25T22:33:17.323+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=get_weather_data_v0, task_id=merge_weather_data, execution_date=20230325T210000, start_date=20230325T223317, end_date=20230325T223317
[2023-03-25T22:33:17.362+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-25T22:33:17.390+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
