[2023-03-25T14:48:45.801+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T04:00:00+00:00 [queued]>
[2023-03-25T14:48:45.813+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T04:00:00+00:00 [queued]>
[2023-03-25T14:48:45.814+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:48:45.814+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T14:48:45.814+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:48:45.876+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 04:00:00+00:00
[2023-03-25T14:48:45.886+0000] {standard_task_runner.py:55} INFO - Started process 262 to run task
[2023-03-25T14:48:45.891+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'scheduled__2023-03-25T04:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpbjxi4dkh']
[2023-03-25T14:48:45.895+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask download_weather_data
[2023-03-25T14:48:45.998+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T04:00:00+00:00 [running]> on host dbbe6b1163d2
[2023-03-25T14:48:46.120+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T04:00:00+00:00
[2023-03-25T14:48:46.993+0000] {get_weather_data.py:84} ERROR - An error occurred when trying to retrieve the weather data. Error:
Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T14:48:46.995+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 81, in download_weather_data
    raise ValueError("Could not retrieve weather data. Response code: {response.status_code}.\nResponse message: {response.text}")
ValueError: Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T14:48:47.008+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T040000, start_date=20230325T144845, end_date=20230325T144847
[2023-03-25T14:48:47.131+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 8 for task download_weather_data (Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}; 262)
[2023-03-25T14:48:47.188+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T14:48:47.217+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-25T19:30:21.254+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T04:00:00+00:00 [queued]>
[2023-03-25T19:30:21.276+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T04:00:00+00:00 [queued]>
[2023-03-25T19:30:21.276+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T19:30:21.276+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T19:30:21.277+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T19:30:21.311+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 04:00:00+00:00
[2023-03-25T19:30:21.317+0000] {standard_task_runner.py:55} INFO - Started process 216 to run task
[2023-03-25T19:30:21.321+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'scheduled__2023-03-25T04:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpwfwq4ged']
[2023-03-25T19:30:21.323+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask download_weather_data
[2023-03-25T19:30:21.420+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T04:00:00+00:00 [running]> on host 81679e29af39
[2023-03-25T19:30:21.558+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T04:00:00+00:00
[2023-03-25T19:30:23.751+0000] {get_weather_data.py:45} INFO - Decompressing .gz weather data...
[2023-03-25T19:30:23.781+0000] {get_weather_data.py:47} INFO - Decompression successful!
[2023-03-25T19:30:23.781+0000] {get_weather_data.py:54} INFO - Parsing json weather data...
[2023-03-25T19:30:24.221+0000] {get_weather_data.py:56} INFO - Parsing successful!
[2023-03-25T19:30:24.222+0000] {get_weather_data.py:68} INFO - Writing current data...
[2023-03-25T19:30:24.223+0000] {get_weather_data.py:84} ERROR - An error occurred when trying to retrieve the weather data. Error:
Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2023-03-25T19:30:24.223+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 69, in download_weather_data
    data.to_parquet(path=f"{base_output_path}/current_weather_data.parquet", engine="fastparquet", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 412, in to_parquet
    impl = get_engine(engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 66, in get_engine
    return FastParquetImpl()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 255, in __init__
    "fastparquet", extra="fastparquet is required for parquet support."
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2023-03-25T19:30:24.252+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T040000, start_date=20230325T193021, end_date=20230325T193024
[2023-03-25T19:30:24.291+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task download_weather_data (Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.; 216)
[2023-03-25T19:30:24.360+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T19:30:24.591+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
