[2023-03-25T14:48:47.623+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T13:00:00+00:00 [queued]>
[2023-03-25T14:48:47.640+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T13:00:00+00:00 [queued]>
[2023-03-25T14:48:47.640+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:48:47.640+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T14:48:47.640+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:48:47.668+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 13:00:00+00:00
[2023-03-25T14:48:47.678+0000] {standard_task_runner.py:55} INFO - Started process 288 to run task
[2023-03-25T14:48:47.683+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'scheduled__2023-03-25T13:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpcyfg0pfg']
[2023-03-25T14:48:47.685+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask download_weather_data
[2023-03-25T14:48:47.758+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T13:00:00+00:00 [running]> on host dbbe6b1163d2
[2023-03-25T14:48:47.854+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T13:00:00+00:00
[2023-03-25T14:48:48.555+0000] {get_weather_data.py:84} ERROR - An error occurred when trying to retrieve the weather data. Error:
Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T14:48:48.557+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 81, in download_weather_data
    raise ValueError("Could not retrieve weather data. Response code: {response.status_code}.\nResponse message: {response.text}")
ValueError: Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T14:48:48.570+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T130000, start_date=20230325T144847, end_date=20230325T144848
[2023-03-25T14:48:48.587+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 17 for task download_weather_data (Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}; 288)
[2023-03-25T14:48:48.617+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T14:48:48.775+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-25T19:30:23.614+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T13:00:00+00:00 [queued]>
[2023-03-25T19:30:23.636+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T13:00:00+00:00 [queued]>
[2023-03-25T19:30:23.636+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T19:30:23.636+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T19:30:23.637+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T19:30:23.918+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 13:00:00+00:00
[2023-03-25T19:30:23.937+0000] {standard_task_runner.py:55} INFO - Started process 246 to run task
[2023-03-25T19:30:23.947+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'scheduled__2023-03-25T13:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmp6iupkdj6']
[2023-03-25T19:30:23.950+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask download_weather_data
[2023-03-25T19:30:24.142+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T13:00:00+00:00 [running]> on host 81679e29af39
[2023-03-25T19:30:24.330+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T13:00:00+00:00
[2023-03-25T19:30:25.308+0000] {get_weather_data.py:45} INFO - Decompressing .gz weather data...
[2023-03-25T19:30:25.336+0000] {get_weather_data.py:47} INFO - Decompression successful!
[2023-03-25T19:30:25.336+0000] {get_weather_data.py:54} INFO - Parsing json weather data...
[2023-03-25T19:30:25.520+0000] {get_weather_data.py:56} INFO - Parsing successful!
[2023-03-25T19:30:25.520+0000] {get_weather_data.py:68} INFO - Writing current data...
[2023-03-25T19:30:25.521+0000] {get_weather_data.py:84} ERROR - An error occurred when trying to retrieve the weather data. Error:
Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2023-03-25T19:30:25.521+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 69, in download_weather_data
    data.to_parquet(path=f"{base_output_path}/current_weather_data.parquet", engine="fastparquet", index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 412, in to_parquet
    impl = get_engine(engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 66, in get_engine
    return FastParquetImpl()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 255, in __init__
    "fastparquet", extra="fastparquet is required for parquet support."
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/_optional.py", line 118, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.
[2023-03-25T19:30:25.537+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T130000, start_date=20230325T193023, end_date=20230325T193025
[2023-03-25T19:30:25.559+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 16 for task download_weather_data (Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.; 246)
[2023-03-25T19:30:25.581+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T19:30:25.625+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
