[2023-03-25T23:23:17.804+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data_v0.merge_weather_data scheduled__2023-03-25T22:00:00+00:00 [queued]>
[2023-03-25T23:23:17.814+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data_v0.merge_weather_data scheduled__2023-03-25T22:00:00+00:00 [queued]>
[2023-03-25T23:23:17.814+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T23:23:17.814+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T23:23:17.814+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T23:23:17.827+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): merge_weather_data> on 2023-03-25 22:00:00+00:00
[2023-03-25T23:23:17.831+0000] {standard_task_runner.py:55} INFO - Started process 419 to run task
[2023-03-25T23:23:17.835+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data_v0', 'merge_weather_data', 'scheduled__2023-03-25T22:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmp3bre6128']
[2023-03-25T23:23:17.838+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask merge_weather_data
[2023-03-25T23:23:17.916+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data_v0.merge_weather_data scheduled__2023-03-25T22:00:00+00:00 [running]> on host 377ca406d6db
[2023-03-25T23:23:18.000+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data_v0
AIRFLOW_CTX_TASK_ID=merge_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T22:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T22:00:00+00:00
[2023-03-25T23:23:18.001+0000] {get_weather_data.py:125} INFO - Loading current weather data file...
[2023-03-25T23:23:18.057+0000] {get_weather_data.py:127} INFO - Loading AUX csv file for merge...
[2023-03-25T23:23:18.060+0000] {get_weather_data.py:134} INFO - Merging files...
[2023-03-25T23:23:18.068+0000] {get_weather_data.py:142} INFO - Saving merged file...
[2023-03-25T23:23:18.085+0000] {get_weather_data.py:144} INFO - Saved file successfully at /opt/***/dags/data//current/current_weather_data_merged.parquet
[2023-03-25T23:23:18.085+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-25T23:23:18.094+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=get_weather_data_v0, task_id=merge_weather_data, execution_date=20230325T220000, start_date=20230325T232317, end_date=20230325T232318
[2023-03-25T23:23:18.166+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-25T23:23:18.194+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
